apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
          volumeMounts:
            - name: workdir
              mountPath: /var/www/html
        initContainers:
          - name: install
            image: busybox:1.28
            command:
              - wget
              - "-O"
              - "/work-dir/index.html"
              - http://kubernetes.io
            volumeMounts:
              - name: workdir
                mountPath: "/work-dir"
          dnsPolicy: Default
            volumes:
                - name: workdir
                  emptyDir: { }
